web/application/__init__.py
import os

from application.db_manager import DbManager

from flask_login import LoginManager, UserMixin
from flask import Flask, redirect, url_for


def redirect_to_login():
    return redirect(url_for('auth.login'))


def create_app(config=None):
    app = Flask(__name__)
    app.config.from_mapping(
        TEMPLATES_AUTO_RELOAD=True,
        # TODO replace with env variable
        SECRET_KEY='secret',
        BOOK_PATH='/var/books',
        # Database variables
        DATABASE_URL=os.environ['DATABASE_URL'],
        DATABASE_NAME=None,
    )

    if config is not None:
        app.config.update(config)

    login_manager = LoginManager()
    login_manager.unauthorized_handler(redirect_to_login)
    login_manager.init_app(app)

    @app.route('/')
    def default():
        return redirect('/login')

    @login_manager.user_loader
    def user_loader(login):
        db_manager = DbManager.Manager()
        if db_manager.get_user(login) is None:
            return
        user = UserMixin()
        user.id = login
        return user

    # Register all blueprints to the app
    from application.views import (
        auth,
        article,
        request,
        store,
        approve,
    )

    app.register_blueprint(auth.bp)
    app.register_blueprint(article.bp)
    app.register_blueprint(request.bp)
    app.register_blueprint(store.bp)
    app.register_blueprint(approve.bp)

    return app

web/application/views/approve.py
from flask import (
    Blueprint,
    request,
)
from flask_login import login_required, current_user

from application.db_manager import DbManager

bp = Blueprint('approve', __name__)


@bp.route('/to_approve', methods=['GET'])
@login_required
def get_books_to_approve():
    db_manager = DbManager.Manager()
    user = db_manager.get_user(current_user.id)

    if user['role'] != 'admin':
        return {}

    books = db_manager.get_list_of_books_to_approve()

    book_dict = {}
    i = 0
    for book in books:
        book['_id'] = str(book['_id'])
        book_dict[i] = book
        i += 1

    return book_dict


@bp.route('/approvals', methods=['GET', 'POST'])
@login_required
def approvals():
    db_manager = DbManager.Manager()
    user = db_manager.get_user(current_user.id)

    if user['role'] != 'admin':
        return {}

    action = ''
    article_id = ''

    if 'action' in request.form:
        action = request.form['action']
    if 'article_id' in request.form:
        article_id = request.form['article_id']

    if action == 'Approve':
        db_manager.approve_article(article_id)
    elif action == 'Decline':
        db_manager.delete_article(article_id)

    return {}

web/application/views/article.py
from flask import (
    Blueprint,
    request,
)

from application.db_manager import DbManager

bp = Blueprint('article', __name__)


@bp.route('/choose_article', methods=['GET', 'POST'])
def choose_article():
    db_manager = DbManager.Manager()

    tag = ''

    if 'data' in request.form:
        tag = request.form['data']

    book_list = db_manager.get_books_by_tag(tag)

    book_dict = {}
    i = 0
    for book in book_list:
        book['_id'] = str(book['_id'])
        book_dict[i] = book
        i += 1

    return book_dict


@bp.route('/search_article', methods=['GET', 'POST'])
def search_article():
    db_manager = DbManager.Manager()

    book_title = ''
    if 'data' in request.form:
        book_title = request.form['data']
    print(book_title)
    book_list = db_manager.get_books_by_title(book_title)
    book_dict = {}
    i = 0
    for book in book_list:
        book['_id'] = str(book['_id'])
        book_dict[i] = book
        i += 1

    return book_dict

web/application/views/auth.py
from flask import (
    Blueprint,
    request,
    redirect,
    url_for,
    render_template,
)

from flask_login import (
    UserMixin,
    login_required,
    current_user,
    login_user,
    logout_user,
)
from application.db_manager import DbManager

bp = Blueprint('auth', __name__)


@bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))


@bp.route('/login', methods=['GET', 'POST'])
def login():
    db_manager = DbManager.Manager()

    if current_user.is_authenticated:
        return redirect(url_for('store.download'))

    if request.method == 'GET':
        return render_template('login.html')

    login = request.form['login']

    match = db_manager.check_validity(
        login,
        request.form['password']
    )
    if match:
        user = UserMixin()
        user.id = login
        login_user(user)
        return redirect(url_for('store.download'))

    return render_template(
        'login.html',
    )

web/application/views/request.py
from application.db_manager import DbManager
from flask import Blueprint, request, redirect, url_for

bp = Blueprint('request', __name__)


@bp.route('/upload_request', methods=['GET', 'POST'])
def upload_request():
    db_manager = DbManager.Manager()
    title = ''

    if 'title' in request.form:
        title = request.form['title']

    db_manager.upload_request(title)
    return redirect(url_for('store.download'))


@bp.route('/delete_request', methods=['GET', 'POST'])
def delete_request():
    db_manager = DbManager.Manager()

    request_id = ''
    if 'data' in request.form:
        request_id = request.form['data']

    db_manager.delete_request(request_id)
    return {}

web/application/views/store.py
import os
from flask import (
    Blueprint,
    request,
    redirect,
    url_for,
    render_template,
)
from flask_login import login_required, current_user

from application.db_manager import DbManager

bp = Blueprint('store', __name__)


@bp.route('/download', methods=['GET', 'POST'])
@login_required
def download():
    db_manager = DbManager.Manager()
    books = db_manager.get_list_of_books()
    requests = db_manager.get_requests()
    user = db_manager.get_user(current_user.id)

    return render_template(
        'download.html',
        books=books,
        requests=requests,
        username=user['login'],
        user_role=user['role'],
    )


@bp.route('/upload', methods=['GET', 'POST'])
def upload_file():
    db_manager = DbManager.Manager()

    filename = ''
    file_book = ''
    title = ''
    file_picture = ''
    file_picture_name = ''
    description = ''
    subject_tag = ''
    course_tag1 = ''
    course_tag2 = ''
    course_tag3 = ''

    if 'file' in request.files:
        filename = request.files['file'].filename
        file_book = request.files['file']

    if 'title' in request.form:
        title = request.form['title']

    if 'file_picture' in request.files:
        file_picture = request.files['file_picture']
        file_picture_name = file_picture.filename

    if 'description' in request.form:
        description = request.form['description']

    if 'subject_tag' in request.form:
        subject_tag = request.form['subject_tag']

    if 'course_tag1' in request.form:
        course_tag1 = request.form['course_tag1']

    if 'course_tag2' in request.form:
        course_tag2 = request.form['course_tag2']

    if 'course_tag3' in request.form:
        course_tag3 = request.form['course_tag3']

    data = {
        'title': title,
        'description': description,
        'filename': filename,
        'img': file_picture_name,
        'subject_tag': subject_tag,
        'course_tag1': course_tag1,
        'course_tag2': course_tag2,
        'course_tag3': course_tag3,
        'approved': 'false',
    }
    db_manager.insert_book(data)

    books_folder = '/var/books'

    covers_dir_name = 'covers'
    images_folder = os.path.join(books_folder, covers_dir_name)

    if not os.path.exists(images_folder):
        os.mkdir(images_folder)
        print(f'Directory {images_folder} Created ')
    else:
        print(f'Directory {images_folder} already exists')

    file_picture.save(os.path.join(images_folder, file_picture_name))

    file_book.save(os.path.join(books_folder, filename))
    return redirect(url_for('store.download'))

web/application/templates/download.html
<!DOCTYPE html>
<html lang="en">

<head>
  <script src="/static/vendor/jquery/jquery.min.js"></script>
  <script src="/static/js/download.min.js"></script>
  <link rel="stylesheet" href="/static/css/download.min.css">
  <link rel="shortcut icon" href="/static/img/favicon.ico" type="image/x-icon">
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Book Harbour</title>
</head>

<body>
<header class="header">
  <div class="header__welcome">
    <h2 class="header__welcome_text">Welcome to the Book Harbour, <a href="/logout" class="logout" data-hover="Logout.">{{username}}.</a></h2>
  </div>
  <!--        If the user is not admin -> show this one: -->
  {% if user_role != 'admin' %}
  <div class="header__upload">
    <h2 class="header__upload_text">Request materials.</h2>
  </div>
  <!--        If the user is admin -> show this one: -->
  {% else %}
  <div class="header__upload">
    <h2 class="header__upload_text_approval">Uploaded materials.</h2>
    <h2 class="header__upload_text">Requested materials.</h2>
  </div>
  {% endif %}

</header>
<main class="main">
  <sidebar class="main__sidebar">
    <div class="main__sidebar__search">
      <p class="main__sidebar__search_desctiption">Search:</p>
      <input type="search" class="main__sidebar__search_input"/>
    </div>
    <div class="main__sidebar__categories">
      <p class="main__sidebar__categories_desctiption">Choose from:</p>
      <select class="main__sidebar__categories_input" id="sidebar_category">
        <option value="subject">Subject</option>
        <option value="cnumber">Course</option>
      </select>
    </div>
    <div class="main__sidebar__choose">
      <div class="main__sidebar__choose_subject" id="sidebar_subjects">
        <ul>
          <li class="choose_category">Mathematics</li>
          <li class="choose_category">Software Engineering</li>
          <li class="choose_category">Data Science</li>
          <li class="choose_category">Computer Science</li>
        </ul>
      </div>
      <div class="main__sidebar__choose_course" id="sidebar_courses">
        <ul>
          <li class="choose_category">Calculus</li>
          <li class="choose_category">Probability and Statistics</li>
          <li class="choose_category">Computer Architecture</li>
          <li class="choose_category">Operating Systems</li>
          <li class="choose_category">Computer Networks</li>
          <li class="choose_category">Philosophy</li>
          <li class="choose_category">Data Modelling and Databases</li>
          <li class="choose_category">Digital Signal Processing</li>
        </ul>
      </div>
    </div>
  </sidebar>
  <div class="main__content">
    {% for book in books %} {% set id = book['_id'] %} {% set title = book['title'] %} {% set description = book['description'] %} {% set img = book['img'] %} {% set filename = book['filename'] %} {%
    set filepath = "/static/books/" + filename%}

    <article class="main__content__article" id="{{id}}">
      <div class="main__content__article_wrapper">
        <img src="/static/books/covers/{{img}}" alt="" class="main__content__article__image">
        <h1 class="main__content__article__header">{{title}}</h1>
        <div class="main__content__article__description">
          {{description}}
        </div>
      </div>
      <div class="main__content__article__buttons">
        <a class="main__content__article__download" href="{{filepath}}" download="{{filename}}">Download</a>
      </div>
      <h3 class="main__content__article__pageNum"></h3>
    </article>
    {% endfor %}

    <article class="main__content__article_rules" id="main__content__article_rules">
      <div class="main__content__article_wrapper">
        <h1 class="main__content__article__header">The Library Pirate Code</h1>
        <div class="main__content__article__description">
          <p style="text-indent: 1em">This is Pirate Code: set of rules of Book Harbour. Following this rules will lead you to successful contribution to our website.
            Important: this rules should be followed by contributors only, if you use website and don’t contribute you are allowed not to read this.

          </p>
          <br>
          <p style="text-indent: 1em">
            When you try to Contribute to our project, you create an upload request, which is not necessarily will be accepted by administrator, it can also be declined in case if you do not follow
            next rules:
          </p>
          <div class="main__content__article__description_rules">
            <ul>
              <li>Our site is based on anonymous work, when you contribute to project, you are not allowed to specify your credentials, organization or something that can threat your anonymity.</li>
              <li>We do not accept descriptions or pictures that have potentially offensive to any group of people content.</li>
              <li>Materials uploaded to the site should match with their title and description, don’t waste time of people, who search for needed materials and find there something that doesn’t match
                their expectations.
              </li>
              <li>Don’t upload short versions of books: either full or nothing.</li>
              <li>(optional, but preferred) Add tags to your book, that will simplify search for the others.</li>
            </ul>
          </div>
        </div>
        <a class="download_rules" href="/static/howto/README.md" download="README.md">How to Use</a>
      </div>

    </article>

    <!--            If the user is not admin, show this:-->
    {% if user_role != 'admin' %}
    <article class="main__content__article_upload_request">
      <form enctype="multipart/form-data" method="post" action="{{url_for('request.upload_request')}}" , class="main__content__article_upload_request_form">
        <div class="main__content__article_upload__input">
          <div class="main__content__article_upload__input_wrapper">
            <p>Book name</p>
            <input name="title" type="text" required>
          </div>
        </div>
        <div class="main__content__article_upload__buttons">
          <button type="submit" value="upload" class="main__content__article_upload__download">Request</button>
        </div>
      </form>
    </article>
    {% else %}
    <!--            If the user is admin, show this: -->
    <article class="main__content__article_upload_request" id="article_requests">
      <h1 class="main__content__article__header">Requested Books</h1>
      <ul class="list_of_requests" id="list_of_requests">
        {% for request in requests %}
        {% set title = request['title'] %}
        {% set id = request['_id'] %}
        <li><p>{{title}}</p>
          <p hidden>{{id}}</p>
          <button class="main__content__article_upload_newTag delete_request">Delete</button>
        </li>
        {% endfor %}
      </ul>
    </article>
    {% endif %}
    <!--            Do not touch everything after this line: -->

    <article class="main__content__article_upload" id="two">
      <form id="uploadbanner" enctype="multipart/form-data" method="post" action="{{url_for('store.upload_file')}}" , class="main__content__article_upload_form">
        <div class="main__content__article_upload__input">
          <div class="main__content__article_upload__input_wrapper">
            <p>Book name</p>
            <input name="title" type="text" required>
          </div>
          <div class="main__content__article_upload__input_wrapper">
            <p>Subject Tag: </p>
            <select name='subject_tag' class="main__sidebar__choose_subject">
              <option value="Mathematics">Mathematics</option>
              <option value="SoftwareEngineering">Software Engineering</option>
              <option value="DataScience">Data Science</option>
              <option value="ComputerScience">Computer Science</option>
            </select>
          </div>
          <div class="main__content__article_upload__input_wrapper" id="tags_one">
            <p>Course Tag (I): </p>
            <div class="main__content__article_select">
              <select name='course_tag1' class="main__sidebar__choose_subject">
                <option value="Calculus">Calculus</option>
                <option value="ProbabilityAndStatistics">Probability and Statistics</option>
                <option value="ComputerArchitecture">Computer Architecture</option>
                <option value="OperatingSystems">Operating Systems</option>
                <option value="ComputerNetworks">Computer Networks</option>
                <option value="Philosophy">Philosophy</option>
                <option value="Calculus">Calculus</option>
                <option value="Data ModellingAndDatabases">Data Modelling and Databases</option>
                <option value="DigitalSignalProcessing">Digital Signal Processing</option>
              </select>
              <button class="main__content__article_upload_newTag" id="newTag_one">Add new tag</button>
            </div>
          </div>
          <div class="main__content__article_upload__input_wrapper">
            <p>Book description</p>
            <textarea name="description" rows="4" cols="50"></textarea>
          </div>
          <div class="main__content__article_upload__input_wrapper">
            <p>Book file</p>
            <input name="file" type="file" id="file" class="inputfile" required>
            <label for="file" id='file_label'>Choose file</label>
          </div>
          <div class="main__content__article_upload__input_wrapper">
            <p>Book Image</p>
            <input name="file_picture" type="file" id="file_picture" class="inputfile">
            <label for="file_picture" id='file_picture_label'>Choose file</label>
          </div>
        </div>
        <div class="main__content__article_upload__buttons">
          <button type="submit" value="upload" class="main__content__article_upload__download">Upload</button>
        </div>
      </form>
    </article>
  </div>
</main>
<footer class="footer">
  <div class="footer__rules">
    <h2 class="footer__rules_text">Usage rules.</h2>
  </div>
  <div class="footer__upload">
    <h2 class="footer__upload_text footer__upload_text_contr">Contribute to the project.</h2>
  </div>
</footer>
<div id="hider"></div>
<div id="no_support">
  <h1>Sorry, we do not support devices with screen size less than 1680 x 1050</h1>
</div>
</body>

</html>

web/application/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <script src="/static/vendor/jquery/jquery.min.js"></script>
    <script src="/static/js/login.min.js"></script>
    <link rel="stylesheet" href="/static/css/login.min.css">
    <link rel="shortcut icon" href="/static/img/favicon.ico" type="image/x-icon">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bookharbor Login</title>
</head>
<body>
    <div class="login">
        <div class="login__desc">
            <h1 class="login__desc_text">Login</h1>
            <div class="login__desc_line"></div>
        </div>
        <form class="login__controls" id="login_form" method="post">
            <div class="login__controls_username">
                <p class="login__controls_username_text">Username: </p>
                <input type="text" name="login" calss="login__controls_username_input" id="username_input" required autocomplete="off"/>
            </div>
            <div class="login__controls_password">
                <p class="login__controls_password_text">Password: </p>
                <input type="password" name="password" class="login__controls_password_input" id="password_input" required/>
            </div>
            <div class="login__controls_buttons">
                <div class="login__controls_buttons_spacer"></div>
                <input id="login_button" type="submit" value="Login" class="login__controls_buttons_btn">
            </div>
        </form>
    </div>
    <div id="hider"></div>
</body>
</html>